stages:
- stage: Build
  jobs:
  - job: Build
    strategy:
      matrix:
        'Windows':
          VM_IMAGE: 'windows-2019'
        'Linux':
          VM_IMAGE: 'Ubuntu 16.04'
        'macOS':
          VM_IMAGE: 'macOS-latest'
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    - template: build/stages/build.yml

- stage: Docker
  condition: succeeded()
  jobs:
  - job: Docker
    strategy:
      matrix:
        'Windows':
          VM_IMAGE: 'windows-2019'
        'Linux':
          VM_IMAGE: 'Ubuntu 16.04'
    pool:
      vmImage: $(VM_IMAGE)
    steps:
    - template: build/stages/docker.yml

- stage: Publish
  condition: succeeded()
  jobs:
  - job: Publish
    pool:
      vmImage: windows-2019
    steps:
    - template: build/stages/publish.yml    
