parameters:
  name: ''
  vmImage: ''

jobs:
- job: Artifacts_Test_${{ parameters.name }}
  displayName: 'Artifacts Test ${{ parameters.name }}'
  pool:
    vmImage: ${{ parameters.vmImage }}
  dependsOn: Generator
  strategy:
    matrix: $[ dependencies['Generator'].outputs['Map_${{ parameters.name }}.dockerConfigs'] ]
  steps:
  - template: common-steps.yml
  - task: DownloadPipelineArtifact@2
    displayName: 'Download pipeline artifacts'
    inputs:
      source: current
      path: $(Build.SourcesDirectory)
      artifact: storage
  - pwsh: ./build.ps1 -target Artifacts-Test -DockerDistro $(DISTRO) -DockerDotnetVersion $(DOTNET_VERSION)
    displayName: '[Docker Test Artifacts]'
