parameters:
  name: ''
  vmImage: ''

jobs:
- job: Docker_${{ parameters.name }}
  displayName: 'Docker ${{ parameters.name }}'
  pool:
    vmImage: ${{ parameters.vmImage }}
  dependsOn: Generator
  strategy:
    matrix: $[ dependencies['Generator'].outputs['Map_${{ parameters.name }}.dockerConfigs'] ]
  steps:
  - template: common-steps.yml
  - task: DownloadPipelineArtifact@2
    displayName: 'Download pipeline artifacts'
    inputs:
      source: current
      path: $(Build.SourcesDirectory)
      artifact: storage
  - pwsh: ./build.ps1 -target Publish-DockerHub -DockerDistro $(DISTRO) -DockerDotnetVersion $(DOTNET_VERSION)
    displayName: '[Docker build]'
    env:
      DOCKER_USERNAME: $(DOCKER_USERNAME)
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)
      ENABLED_PUBLISH_DOCKER: $(ENABLED_PUBLISH_DOCKER)
